# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=200, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
    ]
